title: "Blog Title"
author: "Blog Author"
description: "Thant Sin Khine Aung's personal blog"

remote_theme: niklasbuschmann/contrast@v2.11

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

plugins:
  - jekyll-remote-theme